dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('finlab.urls', namespace='finlab')),

    path('administration/', include('administration.urls', namespace='administration')),

    path('analytics/', include('analytics.urls', namespace='analytics')),


    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Finlab Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"

finlab/urls.py
import imp
from django.urls import path, include
from finlab import finlab_views

app_name = 'finlab'
urlpatterns = [
    # Users
    path('users/', include("users.urls")),

    path('', finlab_views.index, name="index"),
    path('index/', finlab_views.index, name="index"),
    path('index-2/', finlab_views.index2, name="index-2"),
    path('banking/', finlab_views.banking, name="banking"),
    path('ticketing/', finlab_views.ticketing, name="ticketing"),
    path('crypto/', finlab_views.crypto, name="crypto"),
    path('invoice/', finlab_views.invoice, name="invoice"),
    path('contact/', finlab_views.contact, name="contact"),
    path('kanban/', finlab_views.kanban, name="kanban"),
    path('file-manager/', finlab_views.file_manager, name="file-manager"),
    path('user/', finlab_views.user, name="user"),
    path('calendar/', finlab_views.calendar, name="calendar"),
    path('to-do-list/', finlab_views.to_do_list, name="to-do-list"),
    path('chat/', finlab_views.chat, name="chat"),
    path('activity/', finlab_views.activity, name="activity"),
    path('app-profile/', finlab_views.app_profile, name="app-profile"),
    path('post-details/', finlab_views.post_details, name="post-details"),
    path('email-compose/', finlab_views.email_compose, name="email-compose"),
    path('email-inbox/', finlab_views.email_inbox, name="email-inbox"),
    path('email-read/', finlab_views.email_read, name="email-read"),
    path('app-calendar/', finlab_views.app_calendar, name="app-calendar"),

    path('ecom-checkout/', finlab_views.ecom_checkout, name="ecom-checkout"),
    path('ecom-customers/', finlab_views.ecom_customers, name="ecom-customers"),
    path('ecom-invoice/', finlab_views.ecom_invoice, name="ecom-invoice"),
    path('ecom-product-detail/', finlab_views.ecom_product_detail, name="ecom-product-detail"),
    path('ecom-product-grid/', finlab_views.ecom_product_grid, name="ecom-product-grid"),
    path('ecom-product-list/', finlab_views.ecom_product_list, name="ecom-product-list"),
    path('ecom-product-order/', finlab_views.ecom_product_order, name="ecom-product-order"),

    path('chart-chartist/', finlab_views.chart_chartist, name="chart-chartist"),
    path('chart-chartjs/', finlab_views.chart_chartjs, name="chart-chartjs"),
    path('chart-flot/', finlab_views.chart_flot, name="chart-flot"),
    path('chart-morris/', finlab_views.chart_morris, name="chart-morris"),
    path('chart-peity/', finlab_views.chart_peity, name="chart-peity"),
    path('chart-sparkline/', finlab_views.chart_sparkline, name="chart-sparkline"),

    path('ui-accordion/', finlab_views.ui_accordion, name="ui-accordion"),
    path('ui-alert/', finlab_views.ui_alert, name="ui-alert"),
    path('ui-badge/', finlab_views.ui_badge, name="ui-badge"),
    path('ui-button/', finlab_views.ui_button, name="ui-button"),
    path('ui-modal/', finlab_views.ui_modal, name="ui-modal"),
    path('ui-button-group/', finlab_views.ui_button_group, name="ui-button-group"),
    path('ui-list-group/', finlab_views.ui_list_group, name="ui-list-group"),
    path('ui-media-object/', finlab_views.ui_media_object, name="ui-media-object"),
    path('ui-card/', finlab_views.ui_card, name="ui-card"),
    path('ui-carousel/', finlab_views.ui_carousel, name="ui-carousel"),
    path('ui-dropdown/', finlab_views.ui_dropdown, name="ui-dropdown"),
    path('ui-popover/', finlab_views.ui_popover, name="ui-popover"),
    path('ui-progressbar/', finlab_views.ui_progressbar, name="ui-progressbar"),
    path('ui-tab/', finlab_views.ui_tab, name="ui-tab"),
    path('ui-typography/', finlab_views.ui_typography, name="ui-typography"),
    path('ui-pagination/', finlab_views.ui_pagination, name="ui-pagination"),
    path('ui-grid/', finlab_views.ui_grid, name="ui-grid"),

    path('uc-select2/', finlab_views.uc_select2, name="uc-select2"),
    path('uc-nestable/', finlab_views.uc_nestable, name="uc-nestable"),
    path('uc-noui-slider/', finlab_views.uc_noui_slider, name="uc-noui-slider"),
    path('uc-sweetalert/', finlab_views.uc_sweetalert, name="uc-sweetalert"),
    path('uc-toastr/', finlab_views.uc_toastr, name="uc-toastr"),
    path('map-jqvmap/', finlab_views.map_jqvmap, name="map-jqvmap"),
    path('uc-lightgallery/', finlab_views.uc_lightgallery, name="uc-lightgallery"),
    path('uc-lightgallery/', finlab_views.uc_lightgallery, name="uc-lightgallery"),

    path('widget-card/', finlab_views.widget_card, name="widget-card"),
    path('widget-chart/', finlab_views.widget_chart, name="widget-chart"),
    path('widget-list/', finlab_views.widget_list, name="widget-list"),

    path('form-element/', finlab_views.form_element, name="form-element"),
    path('form-wizard/', finlab_views.form_wizard, name="form-wizard"),
    path('form-ckeditor/', finlab_views.form_ckeditor, name="form-ckeditor"),
    path('form-pickers/', finlab_views.form_pickers, name="form-pickers"),
    path('form-validation/', finlab_views.form_validation, name="form-validation"),

    path('form-validation/', finlab_views.form_validation, name="form-validation"),
    path('form-validation/', finlab_views.form_validation, name="form-validation"),

    path('table-bootstrap-basic/', finlab_views.table_bootstrap_basic, name="table-bootstrap-basic"),
    path('table-datatable-basic/', finlab_views.table_datatable_basic, name="table-datatable-basic"),

    # path('page-login/',finlab_views.page_login,name="page-login"),
    # path('page-register/',finlab_views.page_register,name="page-register"),

    path('page-lock-screen/', finlab_views.page_lock_screen, name="page-lock-screen"),
    path('page-forgot-password/', finlab_views.page_forgot_password, name="page-forgot-password"),
    path('page-error-400/', finlab_views.page_error_400, name="page-error-400"),
    path('page-error-403/', finlab_views.page_error_403, name="page-error-403"),
    path('page-error-404/', finlab_views.page_error_404, name="page-error-404"),
    path('page-error-500/', finlab_views.page_error_500, name="page-error-500"),
    path('page-error-503/', finlab_views.page_error_503, name="page-error-503"),
    path('empty-page/', finlab_views.empty_page, name="empty-page"),

]

users/urls.py
from django.urls import path
from users import users_views

urlpatterns = [
    path('', users_views.users, name="users"),
    path('user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('add-user/', users_views.add_user, name="add-user"),
    path('edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),
    path('login/', users_views.login_user, name="login"),
    path('logout/', users_views.logout_user, name="logout"),
    path('groups/', users_views.groups_list, name="groups"),
    path('group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('group-add/', users_views.group_add, name="group-add"),
    path('permissions/', users_views.permissions, name="permissions"),
    path('edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('signup/', users_views.signup, name="signup"),
    path('activate/<uidb64>/<token>/', users_views.activate, name='activate'),
]

templates/finlab/apps/shop/ecom-product-grid.html
{% extends 'finlab/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block message %}
{% include 'finlab/elements/alert.html' %}
{% endblock %}


{% block content %}
<div class="row">
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/1.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">Bonorum et Malorum</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa-solid fa-star-half-stroke"></i></li>
							<li><i class="fa-solid fa-star-half-stroke"></i></li>
						</ul>
						<span class="price">$71.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/2.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">Striped Dress</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
						</ul>
						<span class="price">$159.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/3.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">BBow polka-dot</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
						</ul>
						<span class="price">$357.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/4.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">Z Product 360</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa-solid fa-star-half-stroke"></i></li>
							<li><i class="fa-solid fa-star-half-stroke"></i></li>
						</ul>
						<span class="price">$654.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/5.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">Chair Grey</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
						</ul>
						<span class="price">$369.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/6.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">fox sake withe</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
						</ul>
						<span class="price">$245.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/7.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">Back Bag</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
						</ul>
						<span class="price">$364.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xl-3 col-lg-6 col-sm-6">
		<div class="card">
			<div class="card-body">
				<div class="new-arrival-product">
					<div class="new-arrivals-img-contnent">
						<img class="img-fluid" src="{% static 'finlab/images/product/1.jpg' %}" alt="">
					</div>
					<div class="new-arrival-content text-center mt-3">
						<h4><a href="{% url 'finlab:ecom-product-detail' %}">FLARE DRESS</a></h4>
						<ul class="star-rating">
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa fa-star"></i></li>
							<li><i class="fa-solid fa-star-half-stroke"></i></li>
							<li><i class="fa-solid fa-star-half-stroke"></i></li>
						</ul>
						<span class="price">$548.00</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}


{% block additional_js %}

{% endblock %}

templates/finlab/apps/shop/ecom-product-list.html
{% extends 'finlab/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block message %}
{% include 'finlab/elements/alert.html' %}
{% endblock %}


{% block content %}
<div class="row">
	<div class="col-lg-12 col-xl-6">
		<div class="card">
			<div class="card-body">
				<div class="row m-b-30">
					<div class="col-md-5 col-xxl-12">
						<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'finlab/images/product/2.jpg' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-md-7 col-xxl-12">
						<div class="new-arrival-content position-relative">
							<h4><a href="{% url 'finlab:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
							<div class="comment-review star-rating">
								<ul>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa-solid fa-star-half-stroke"></i></li>
									<li><i class="fa-solid fa-star-half-stroke"></i></li>
								</ul>
								<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
								<p class="price">$320.00</p>
							</div>
							<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
							<p>Product code: <span class="item">0405689</span> </p>
							<p>Brand: <span class="item">Lee</span></p>
							<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-12 col-xl-6">
		<div class="card">
			<div class="card-body">
				<div class="row m-b-30">
					<div class="col-md-5 col-xxl-12">
						<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'finlab/images/product/3.jpg' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-md-7 col-xxl-12">
						<div class="new-arrival-content position-relative">
							<h4><a href="{% url 'finlab:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
							<div class="comment-review star-rating">
								<ul>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa-solid fa-star-half-stroke"></i></li>
									<li><i class="fa-solid fa-star-half-stroke"></i></li>
								</ul>
								<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
								<p class="price">$325.00</p>
							</div>
							<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
							<p>Product code: <span class="item">0405689</span> </p>
							<p>Brand: <span class="item">Lee</span></p>
							<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>                                           
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-12 col-xl-6">
		<div class="card">
			<div class="card-body">
				<div class="row m-b-30">
					<div class="col-md-5 col-xxl-12">
						<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'finlab/images/product/4.jpg' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-md-7 col-xxl-12">
						<div class="new-arrival-content position-relative">
							<h4><a href="{% url 'finlab:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
							<div class="comment-review star-rating">
								<ul>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
								<p class="price">$480.00</p>
							</div>
							<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
							<p>Product code: <span class="item">0405689</span> </p>
							<p>Brand: <span class="item">Lee</span></p>
							<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-12 col-xl-6">
		<div class="card">
			<div class="card-body">
				<div class="row m-b-30">
					<div class="col-md-5 col-xxl-12">
						<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'finlab/images/product/5.jpg' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-md-7 col-xxl-12">
						<div class="new-arrival-content position-relative">
							<h4><a href="{% url 'finlab:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
							<div class="comment-review star-rating">
								<ul>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
								<p class="price">$658.00</p>
							</div>
							<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
							<p>Product code: <span class="item">0405689</span> </p>
							<p>Brand: <span class="item">Lee</span></p>
							<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-12 col-xl-6">
		<div class="card">
			<div class="card-body">
				<div class="row m-b-30">
					<div class="col-md-5 col-xxl-12">
						<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'finlab/images/product/6.jpg' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-md-7 col-xxl-12">
						<div class="new-arrival-content position-relative">
							<h4><a href="{% url 'finlab:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
							<div class="comment-review star-rating">
								<ul>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
								<p class="price">$280.00</p>
							</div>
							<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
							<p>Product code: <span class="item">0405689</span> </p>
							<p>Brand: <span class="item">Lee</span></p>
							<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>                                            
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-12 col-xl-6">
		<div class="card">
			<div class="card-body">
				<div class="row m-b-30">
					<div class="col-md-5 col-xxl-12">
						<div class="new-arrival-product mb-4 mb-xxl-4 mb-md-0">
							<div class="new-arrivals-img-contnent">
								<img class="img-fluid" src="{% static 'finlab/images/product/7.jpg' %}" alt="">
							</div>
						</div>
					</div>
					<div class="col-md-7 col-xxl-12">
						<div class="new-arrival-content position-relative">
							<h4><a href="{% url 'finlab:ecom-product-detail' %}">Solid Women's V-neck Dark T-Shirt</a></h4>
							<div class="comment-review star-rating">
								<ul>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
									<li><i class="fa fa-star"></i></li>
								</ul>
								<span class="review-text">(34 reviews) / </span><a class="product-review" href=""  data-bs-toggle="modal" data-bs-target="#reviewModal">Write a review?</a>
								<p class="price">$600.00</p>
							</div>
							<p>Availability: <span class="item"> In stock <i class="fa fa-check-circle text-success"></i></span></p>
							<p>Product code: <span class="item">0405689</span> </p>
							<p>Brand: <span class="item">Lee</span></p>
							<p class="text-content">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- review -->
	<div class="modal fade" id="reviewModal">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">Review</h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal">
					</button>
				</div>
				<div class="modal-body">
					<form>
						<div class="text-center mb-4">
							<img class="img-fluid rounded" width="78" src="./{% static 'finlab/images/avatar/1.jpg' %}" alt="DexignZone">
						</div>
						<div class="mb-3">
							<div class="rating-widget mb-4 text-center">
								<!-- Rating Stars Box -->
								<div class="rating-stars">
									<ul id="stars">
										<li class="star" title="Poor" data-value="1">
											<i class="fa fa-star fa-fw"></i>
										</li>
										<li class="star" title="Fair" data-value="2">
											<i class="fa fa-star fa-fw"></i>
										</li>
										<li class="star" title="Good" data-value="3">
											<i class="fa fa-star fa-fw"></i>
										</li>
										<li class="star" title="Excellent" data-value="4">
											<i class="fa fa-star fa-fw"></i>
										</li>
										<li class="star" title="WOW!!!" data-value="5">
											<i class="fa fa-star fa-fw"></i>
										</li>
									</ul>
								</div>
							</div>
						</div>
						<div class="mb-3">
							<textarea class="form-control" placeholder="Comment" rows="5"></textarea>
						</div>
						<button class="btn btn-success btn-block">RATE</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}


{% block additional_js %}

{% endblock %}