dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('finlab.urls', namespace='finlab')),

    path('administration/', include('administration.urls', namespace='administration')),

    path('analytics/', include('analytics.urls', namespace='analytics')),


    path('reset_password/', auth_views.PasswordResetView.as_view(form_class=EmailValidationOnForgotPassword),
         name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password/', users_views.change_password, name='change_password'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Finlab Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"

finlab/urls.py
import imp
from django.urls import path, include
from finlab import finlab_views

app_name = 'finlab'
urlpatterns = [
    # Users
    path('users/', include("users.urls")),

    path('', finlab_views.index, name="index"),
    path('index/', finlab_views.index, name="index"),
    path('index-2/', finlab_views.index2, name="index-2"),
    path('banking/', finlab_views.banking, name="banking"),
    path('ticketing/', finlab_views.ticketing, name="ticketing"),
    path('crypto/', finlab_views.crypto, name="crypto"),
    path('invoice/', finlab_views.invoice, name="invoice"),
    path('contact/', finlab_views.contact, name="contact"),
    path('kanban/', finlab_views.kanban, name="kanban"),
    path('file-manager/', finlab_views.file_manager, name="file-manager"),
    path('user/', finlab_views.user, name="user"),
    path('calendar/', finlab_views.calendar, name="calendar"),
    path('to-do-list/', finlab_views.to_do_list, name="to-do-list"),
    path('chat/', finlab_views.chat, name="chat"),
    path('activity/', finlab_views.activity, name="activity"),
    path('app-profile/', finlab_views.app_profile, name="app-profile"),
    path('post-details/', finlab_views.post_details, name="post-details"),
    path('email-compose/', finlab_views.email_compose, name="email-compose"),
    path('email-inbox/', finlab_views.email_inbox, name="email-inbox"),
    path('email-read/', finlab_views.email_read, name="email-read"),
    path('app-calendar/', finlab_views.app_calendar, name="app-calendar"),

    path('ecom-checkout/', finlab_views.ecom_checkout, name="ecom-checkout"),
    path('ecom-customers/', finlab_views.ecom_customers, name="ecom-customers"),
    path('ecom-invoice/', finlab_views.ecom_invoice, name="ecom-invoice"),
    path('ecom-product-detail/', finlab_views.ecom_product_detail, name="ecom-product-detail"),
    path('ecom-product-grid/', finlab_views.ecom_product_grid, name="ecom-product-grid"),
    path('ecom-product-list/', finlab_views.ecom_product_list, name="ecom-product-list"),
    path('ecom-product-order/', finlab_views.ecom_product_order, name="ecom-product-order"),

    path('chart-chartist/', finlab_views.chart_chartist, name="chart-chartist"),
    path('chart-chartjs/', finlab_views.chart_chartjs, name="chart-chartjs"),
    path('chart-flot/', finlab_views.chart_flot, name="chart-flot"),
    path('chart-morris/', finlab_views.chart_morris, name="chart-morris"),
    path('chart-peity/', finlab_views.chart_peity, name="chart-peity"),
    path('chart-sparkline/', finlab_views.chart_sparkline, name="chart-sparkline"),

    path('ui-accordion/', finlab_views.ui_accordion, name="ui-accordion"),
    path('ui-alert/', finlab_views.ui_alert, name="ui-alert"),
    path('ui-badge/', finlab_views.ui_badge, name="ui-badge"),
    path('ui-button/', finlab_views.ui_button, name="ui-button"),
    path('ui-modal/', finlab_views.ui_modal, name="ui-modal"),
    path('ui-button-group/', finlab_views.ui_button_group, name="ui-button-group"),
    path('ui-list-group/', finlab_views.ui_list_group, name="ui-list-group"),
    path('ui-media-object/', finlab_views.ui_media_object, name="ui-media-object"),
    path('ui-card/', finlab_views.ui_card, name="ui-card"),
    path('ui-carousel/', finlab_views.ui_carousel, name="ui-carousel"),
    path('ui-dropdown/', finlab_views.ui_dropdown, name="ui-dropdown"),
    path('ui-popover/', finlab_views.ui_popover, name="ui-popover"),
    path('ui-progressbar/', finlab_views.ui_progressbar, name="ui-progressbar"),
    path('ui-tab/', finlab_views.ui_tab, name="ui-tab"),
    path('ui-typography/', finlab_views.ui_typography, name="ui-typography"),
    path('ui-pagination/', finlab_views.ui_pagination, name="ui-pagination"),
    path('ui-grid/', finlab_views.ui_grid, name="ui-grid"),

    path('uc-select2/', finlab_views.uc_select2, name="uc-select2"),
    path('uc-nestable/', finlab_views.uc_nestable, name="uc-nestable"),
    path('uc-noui-slider/', finlab_views.uc_noui_slider, name="uc-noui-slider"),
    path('uc-sweetalert/', finlab_views.uc_sweetalert, name="uc-sweetalert"),
    path('uc-toastr/', finlab_views.uc_toastr, name="uc-toastr"),
    path('map-jqvmap/', finlab_views.map_jqvmap, name="map-jqvmap"),
    path('uc-lightgallery/', finlab_views.uc_lightgallery, name="uc-lightgallery"),
    path('uc-lightgallery/', finlab_views.uc_lightgallery, name="uc-lightgallery"),

    path('widget-card/', finlab_views.widget_card, name="widget-card"),
    path('widget-chart/', finlab_views.widget_chart, name="widget-chart"),
    path('widget-list/', finlab_views.widget_list, name="widget-list"),

    path('form-element/', finlab_views.form_element, name="form-element"),
    path('form-wizard/', finlab_views.form_wizard, name="form-wizard"),
    path('form-ckeditor/', finlab_views.form_ckeditor, name="form-ckeditor"),
    path('form-pickers/', finlab_views.form_pickers, name="form-pickers"),
    path('form-validation/', finlab_views.form_validation, name="form-validation"),

    path('form-validation/', finlab_views.form_validation, name="form-validation"),
    path('form-validation/', finlab_views.form_validation, name="form-validation"),

    path('table-bootstrap-basic/', finlab_views.table_bootstrap_basic, name="table-bootstrap-basic"),
    path('table-datatable-basic/', finlab_views.table_datatable_basic, name="table-datatable-basic"),

    # path('page-login/',finlab_views.page_login,name="page-login"),
    # path('page-register/',finlab_views.page_register,name="page-register"),

    path('page-lock-screen/', finlab_views.page_lock_screen, name="page-lock-screen"),
    path('page-forgot-password/', finlab_views.page_forgot_password, name="page-forgot-password"),
    path('page-error-400/', finlab_views.page_error_400, name="page-error-400"),
    path('page-error-403/', finlab_views.page_error_403, name="page-error-403"),
    path('page-error-404/', finlab_views.page_error_404, name="page-error-404"),
    path('page-error-500/', finlab_views.page_error_500, name="page-error-500"),
    path('page-error-503/', finlab_views.page_error_503, name="page-error-503"),
    path('empty-page/', finlab_views.empty_page, name="empty-page"),

]

users/urls.py
from django.urls import path
from users import users_views

urlpatterns = [
    path('', users_views.users, name="users"),
    path('user-details/<int:id>/', users_views.user_details, name="user-details"),
    path('add-user/', users_views.add_user, name="add-user"),
    path('edit-user/<int:id>/', users_views.edit_user, name="edit-user"),
    path('delete-user/<int:id>/', users_views.delete_user, name="delete-user"),
    path('delete-multiple-user/', users_views.delete_multiple_user, name="delete-multiple-user"),
    path('login/', users_views.login_user, name="login"),
    path('logout/', users_views.logout_user, name="logout"),
    path('groups/', users_views.groups_list, name="groups"),
    path('group-edit/<int:id>/', users_views.group_edit, name="group-edit"),
    path('group-delete/<int:id>/', users_views.group_delete, name="group-delete"),
    path('group-add/', users_views.group_add, name="group-add"),
    path('permissions/', users_views.permissions, name="permissions"),
    path('edit-permissions/<int:id>/', users_views.edit_permissions, name="edit-permissions"),
    path('delete-permissions/<int:id>/', users_views.delete_permissions, name="delete-permissions"),
    path('assign-permissions-to-user/<int:id>/', users_views.assign_permissions_to_user,
         name="assign-permissions-to-user"),
    path('signup/', users_views.signup, name="signup"),
    path('activate/<uidb64>/<token>/', users_views.activate, name='activate'),
]

finlab/models.py
from django.db import models

# Create your models here.

finlab/views.py
from django.shortcuts import render

# Create your views here.

templates/finlab/pages/empty-page.html
{% extends 'finlab/elements/layouts/outer-footer-layout.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block message %}
{% include 'finlab/elements/alert.html' %}
{% endblock %}


{% block content %}

{% endblock %}


{% block additional_js %}

{% endblock %}

templates/finlab/pages/login2.html
<!DOCTYPE html>
<html lang="fr-fr" class="h-100">

    <head>
        {% load static custom_tags %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords" content="" />
        <meta name="author" content="" />
        <meta name="robots" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{{ dz_array.public.title }}" />
        <meta property="og:title" content="{{ dz_array.public.title }}" />
        <meta property="og:description" content="{{ dz_array.public.title }}" />
        <meta property="og:image" content="{{  dz_array.public.social_image_url }}" />
        <meta name="format-detection" content="telephone=no">
        <!-- PAGE TITLE HERE -->
        <title>{{ dz_array.public.title }}</title>
        <!-- FAVICONS ICON -->
        <link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon %}" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">
    
        {% for cssurl in dz_array.pagelevel.finlab.finlab_views.css|getdata:request.path %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        
        {% for cssurl in dz_array.global.css %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        {% block additional_css %}
        {% endblock %}
        
    </head>

    <body class="vh-100">
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-6">
                        <div class="authincation-content">
                            <div class="row no-gutters">
                                <div class="col-xl-12">
                                    <div class="auth-form page-r-logo">
                                        <div class="text-center mb-3">
                                            <a href="{% url 'finlab:index' %}"><img src="{% static 'images/logo-full.png' %}" alt=""></a>
                                            <a href="{% url 'finlab:index' %}"><img src="{% static 'images/logo-full-light.png' %}" alt="" class="light-logo m-auto"></a>
                                        </div>
                                        <h4 class="fs-20 text-center">Sign in your account</h4>
                                        <div class="sign-in-your py-4 px-2">
                                            <form method="post">
                                                <div class="mb-3">
                                                    <label class="mb-1"><strong>Email</strong></label>
                                                    <input type="email" class="form-control" mailto:value="hello@example.com">
                                                </div>
                                                <div class="mb-3">
                                                    <label class="mb-1"><strong>Password</strong></label>
                                                    <input type="password" class="form-control" value="Password">
                                                </div>
                                                <div class="row d-flex justify-content-between mt-4 mb-2">
                                                    <div class="mb-3">
                                                       <div class="form-check custom-checkbox ms-1">
                                                            <input type="checkbox" class="form-check-input" id="basic_checkbox_1">
                                                            <label class="form-check-label" for="basic_checkbox_1">Remember my preference</label>
                                                        </div>
                                                    </div>
                                                    <div class="mb-3">
                                                        <a href="#">Forgot Password?</a>
                                                    </div>
                                                </div>
                                                <div class="text-center">
                                                    <button type="submit" class="btn btn-primary btn-block">Sign Me In</button>
                                                </div>
                                            </form>
                                            <div class="new-account mt-3">
                                                <p>Don't have an account? <a class="text-primary" href="#">Sign Up</a></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.finlab.finlab_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/finlab/pages/page-error-400.html
<!DOCTYPE html>
<html lang="en" class="h-100">

    <head>
        {% load static custom_tags %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords" content="" />
        <meta name="author" content="" />
        <meta name="robots" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{{ dz_array.public.title }}" />
        <meta property="og:title" content="{{ dz_array.public.title }}" />
        <meta property="og:description" content="{{ dz_array.public.title }}" />
        <meta property="og:image" content="{{  dz_array.public.social_image_url }}" />
        <meta name="format-detection" content="telephone=no">
        <!-- PAGE TITLE HERE -->
        <title>{{ dz_array.public.title }}</title>
        <!-- FAVICONS ICON -->
        <link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon %}" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">
    
        {% for cssurl in dz_array.pagelevel.finlab.finlab_views.css|getdata:request.path %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        
        {% for cssurl in dz_array.global.css %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        {% block additional_css %}
        {% endblock %}
        
    </head>

<body class="vh-100">
    <div class="authincation h-100">
        <div class="container h-100">
            <div class="row justify-content-center h-100 align-items-center">
                <div class="col-md-5">
                    <div class="form-input-content text-center error-page">
                        <h1 class="error-text fw-bold">400</h1>
                        <h4><i class="fa fa-thumbs-down text-danger"></i> Bad Request</h4>
                        <p>Your Request resulted in an error</p>
						<div>
                            <a class="btn btn-primary" href="{% url 'finlab:index' %}">Back to Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.finlab.finlab_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/finlab/pages/page-error-403.html
<!DOCTYPE html>
<html lang="en" class="h-100">

    <head>
        {% load static custom_tags %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords" content="" />
        <meta name="author" content="" />
        <meta name="robots" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{{ dz_array.public.title }}" />
        <meta property="og:title" content="{{ dz_array.public.title }}" />
        <meta property="og:description" content="{{ dz_array.public.title }}" />
        <meta property="og:image" content="{{  dz_array.public.social_image_url }}" />
        <meta name="format-detection" content="telephone=no">
        <!-- PAGE TITLE HERE -->
        <title>{{ dz_array.public.title }}</title>
        <!-- FAVICONS ICON -->
        <link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon %}" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">
    
        {% for cssurl in dz_array.pagelevel.finlab.finlab_views.css|getdata:request.path %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        
        {% for cssurl in dz_array.global.css %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        {% block additional_css %}
        {% endblock %}
        
    </head>




    <body class="vh-100">
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-5">
                        <div class="form-input-content text-center error-page">
                            <h1 class="error-text  fw-bold">403</h1>
                            <h4><i class="fa fa-times-circle text-danger"></i> Forbidden Error!</h4>
                            <p>You do not have permission to view this resource.</p>
                            <div>
                                <a class="btn btn-primary" href="{% url 'finlab:index' %}">Back to Home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    


<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.finlab.finlab_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/finlab/pages/page-error-404.html
<!DOCTYPE html>
<html lang="en" class="h-100">

    <head>
        {% load static custom_tags %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords" content="" />
        <meta name="author" content="" />
        <meta name="robots" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{{ dz_array.public.title }}" />
        <meta property="og:title" content="{{ dz_array.public.title }}" />
        <meta property="og:description" content="{{ dz_array.public.title }}" />
        <meta property="og:image" content="{{  dz_array.public.social_image_url }}" />
        <meta name="format-detection" content="telephone=no">
        <!-- PAGE TITLE HERE -->
        <title>{{ dz_array.public.title }}</title>
        <!-- FAVICONS ICON -->
        <link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon %}" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">
    
        {% for cssurl in dz_array.pagelevel.finlab.finlab_views.css|getdata:request.path %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        
        {% for cssurl in dz_array.global.css %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        {% block additional_css %}
        {% endblock %}
        
    </head>




    <body class="vh-100">
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-7">
                        <div class="form-input-content text-center error-page">
                            <h1 class="error-text fw-bold">404</h1>
                            <h4><i class="fa fa-exclamation-triangle text-warning"></i> The page you were looking for is not found!</h4>
                            <p>You may have mistyped the address or the page may have moved.</p>
                            <div>
                                <a class="btn btn-primary" href="{% url 'finlab:index' %}">Back to Home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.finlab.finlab_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/finlab/pages/page-error-500.html
<!DOCTYPE html>
<html lang="en" class="h-100">

    <head>
        {% load static custom_tags %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="keywords" content="" />
        <meta name="author" content="" />
        <meta name="robots" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{{ dz_array.public.title }}" />
        <meta property="og:title" content="{{ dz_array.public.title }}" />
        <meta property="og:description" content="{{ dz_array.public.title }}" />
        <meta property="og:image" content="{{  dz_array.public.social_image_url }}" />
        <meta name="format-detection" content="telephone=no">
        <!-- PAGE TITLE HERE -->
        <title>{{ dz_array.public.title }}</title>
        <!-- FAVICONS ICON -->
        <link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon %}" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">
    
        {% for cssurl in dz_array.pagelevel.finlab.finlab_views.css|getdata:request.path %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        
        {% for cssurl in dz_array.global.css %}
        <link rel="stylesheet" href="{% static cssurl %}" >
        {% endfor %}
        
        {% block additional_css %}
        {% endblock %}
        
    </head>


    <body class="vh-100">    
        <div class="authincation h-100">
            <div class="container h-100">
                <div class="row justify-content-center h-100 align-items-center">
                    <div class="col-md-5">
                        <div class="form-input-content text-center error-page">
                            <h1 class="error-text fw-bold">500</h1>
                            <h4><i class="fa fa-times-circle text-danger"></i> Internal Server Error</h4>
                            <p>You do not have permission to view this resource</p> 
                            <div>
                                <a class="btn btn-primary" href="{% url 'finlab:index' %}">Back to Home</a>
                            </div>	
                        </div>
                    </div>
                </div>
            </div>
        </div>
    





<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.finlab.finlab_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/finlab/pages/page-login.html
<!DOCTYPE html>
<html lang="fr-fr" class="h-100">

<head>
	{% load static custom_tags %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{{ dz_array.public.title }}" />
	<meta property="og:title" content="{{ dz_array.public.title }}" />
	<meta property="og:description" content="{{ dz_array.public.title }}" />
	<meta property="og:image" content="{{  dz_array.public.social_image_url }}" />
	<meta name="format-detection" content="telephone=no">
	<!-- PAGE TITLE HERE -->
	<title>{{ dz_array.public.title }}</title>
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon %}" />
	<link href="https://fonts.googleapis.com/css2?family=Material+Icons"rel="stylesheet">

	{% for cssurl in dz_array.pagelevel.finlab.finlab_views.css|getdata:request.path %}
	<link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
	
	
	{% for cssurl in dz_array.global.css %}
	<link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
	
	{% block additional_css %}
	{% endblock %}
	
</head>

<body class="body  h-100" >
	<div class="container h-100">
		<div class="row h-100 align-items-center justify-contain-center">
			<div class="col-xl-12">
				<div class="card">
					<div class="card-body p-0">
						<div class="row m-0">
							<div class="col-xl-6 col-md-6 sign text-center">
								<div>
									<div class="text-center my-5">
										<a href="{% url 'finlab:index' %}"><img src="{% static 'finlab/images/logo-full.png' %}" alt=""></a>
									</div>
									<img src="{% static 'finlab/images/log.png' %}" class="img-fix bitcoin-img sd-shape7"></img>
								</div>
							</div>
							<div class="col-xl-6 col-md-6">
								<div class="sign-in-your py-4 px-2">
									<h4 class="fs-20">Sign in your account</h4>
									<span>Welcome back! Login with your data that you entered<br> during registration</span>
									<div class="login-social">
										<a href="javascript:void(0);" class="btn d-block btn-primary light my-3"><i class="fab fa-google me-2"></i>Login with Google</a>
										<!-- <a href="javascript:void(0);" class="btn d-block btn-secondary my-3"><i class="fab fa-facebook-f me-2"></i>Login with Facebook</a> -->
									</div>
									<form action="{% url 'finlab:index' %}">
										<div class="mb-3">
											<label class="mb-1"><strong>Email</strong></label>
											<input type="email" class="form-control" value="hello@example.com">
										</div>
										<div class="mb-3">
											<label class="mb-1"><strong>Password</strong></label>
											<input type="password" class="form-control" value="Password">
										</div>
										<div class="row d-flex justify-content-between mt-4 mb-2">
											<div class="mb-3">
												<div class="form-check custom-checkbox ms-1">
													<input type="checkbox" class="form-check-input" id="basic_checkbox_1">
													<label class="form-check-label" for="basic_checkbox_1">Remember my preference</label>
												</div>
											</div>
											<div class="mb-3">
												<a href="{% url 'finlab:page-forgot-password' %}">Forgot Password?</a>
											</div>
										</div>
										<div class="text-center">
											<button type="submit" class="btn btn-primary btn-block">Sign Me In</button>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.finlab.finlab_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>